### ISSUE TITLE
Find a panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by xiaojun207** [zinclabs/zinc#389]
The log like this: 

```
{"level":"info","method":"POST","code":200,"took":4,"time":"2022-08-02T16:10:11+08:00","message":"/es/_bulk"}
panic: runtime error: index out of range [-1]

goroutine 88 [running]:
github.com/zinclabs/zinc/pkg/core.(*walMergeDocs).WriteToShard(0x526bc20?, 0xc00039ce00, 0xffffffffffffffff, 0xc0004c4e00)
        /Users/root/go/src/zinc/pkg/core/index_shards_wal.go:364 +0x1856
github.com/zinclabs/zinc/pkg/core.(*walMergeDocs).WriteTo(0xc0004c4db8, 0xc000be9680?, 0xc0004c4e00, 0x0)
        /Users/root/go/src/zinc/pkg/core/index_shards_wal.go:329 +0xef
github.com/zinclabs/zinc/pkg/core.(*IndexShard).ConsumeWAL(0xc00039ce00)
        /Users/root/go/src/zinc/pkg/core/index_shards_wal.go:213 +0x8aa
github.com/zinclabs/zinc/pkg/core.(*IndexShardWALList).ConsumeWAL.func1()
        /Users/root/go/src/zinc/pkg/core/index_shards_wallist.go:90 +0x70
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/root/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:72 +0xa5

Process finished with the exit code 2


```

The code is current main branch

**Comment by hengfeiyang** [comment]
Yeah, i had got this error, you can have a try with latest code of main branch.

**Comment by xiaojun207** [comment]
> 

I have tried agin with latest code of main branch, but the problem still exists

**Comment by hengfeiyang** [comment]
What can i do to got the same error

**Comment by xiaojun207** [comment]
This problem can be reproduced using the following methods

POST /es/_bulk

body:
```
{"index":{"_index":"fluent.info-20220802","_type":"_doc"}}
{"pid":16,"ppid":7,"worker":0,"message":"starting fluentd worker pid=16 ppid=7 worker=0","@timestamp":"2022-08-02T10:31:09.273261260+00:00","@log_name":"fluent.info"}
{"index":{"_index":"fluent.info-20220802","_type":"_doc"}}
{"port":24224,"bind":"0.0.0.0","message":"listening port port=24224 bind=\"0.0.0.0\"","@timestamp":"2022-08-02T10:31:09.279217000+00:00","@log_name":"fluent.info"}
{"index":{"_index":"fluent.info-20220802","_type":"_doc"}}
{"worker":0,"message":"fluentd worker is now running worker=0","@timestamp":"2022-08-02T10:31:09.279806160+00:00","@log_name":"fluent.info"}
```

**Comment by hengfeiyang** [comment]
I tried this no problem, can you clear data then try again?

**Comment by xiaojun207** [comment]
> 
This problem may be caused by dirty data. After clearing the data, the problem disappears.
