### ISSUE TITLE
Bluge makeslice cap out of range

### ISSUE THREAD

**Issue by almartino** [zinclabs/zinc#556]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
Make zinc work on a kubernetes cluster.
**What action did you take?**
Installed the latest available version of zinc with the provided helm file.
**What action/response/output did you expect?**
Search requests should work as in local docker-compose environment.
**What actually happened?**
Panics on the zinc pod.
**How to reproduce the issue?**
Follow the installation [steps](https://docs.zincsearch.com/installation/) in the "helm" section.
**What version of ZincSearch are you using?**
I executed the same query on two versions by changing the `tag` field on helm `values.yaml` file.
- 0.3.3
- 0.3.2

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**
The invoked api works on a local zinc search (docker container).

Code snipped of the invoked resource:
```
        q := query.MatchZ("name", name)
	q.SetSize(1)
	res, _, err := s.client.Search.Search(ctx, index).Query(q).Execute()
	if err != nil {
		return nil, err
	}
```
`query.MatchZ` is:
```go
// MatchZ returns a MetaMatchQuery already finalized into a MetaZincQuery
func MatchZ(field, query string) zinc.MetaZincQuery {
	return zinc.MetaZincQuery{
		Query: &zinc.MetaQuery{
			Match: Match(field, query),
		},
	}
}

// Match returns a MetaMatchQuery
func Match(field, query string, boost ...*float32) *map[string]zinc.MetaMatchQuery {
	var b *float32
	if len(boost) == 1 {
		b = boost[0]
	}
	return &map[string]zinc.MetaMatchQuery{
		field: {
			Query: &query,
			Boost: b,
		},
	}
}
```
**Any attachments/screenshots?**
```
panic: runtime error: makeslice: cap out of range

goroutine 115 [running]:
github.com/blugelabs/bluge/search/collector.newStoreSlice(...)
	/go/pkg/mod/github.com/zinclabs/bluge@v1.1.5/search/collector/slice.go:26
github.com/blugelabs/bluge/search/collector.newTopNCollector(0xfffffffffffffffe, 0x0, {0xc00000ec30, 0x1, 0x1}, 0x0)
	/go/pkg/mod/github.com/zinclabs/bluge@v1.1.5/search/collector/topn.go:102 +0x266
github.com/blugelabs/bluge/search/collector.NewTopNCollector(...)
	/go/pkg/mod/github.com/zinclabs/bluge@v1.1.5/search/collector/topn.go:64
github.com/blugelabs/bluge.(*TopNSearch).Collector(0xc0000d4000?)
	/go/pkg/mod/github.com/zinclabs/bluge@v1.1.5/search.go:180 +0x7d
github.com/blugelabs/bluge.(*Reader).Search(0xc0008bec60, {0x3c3b7e0, 0xc000114000}, {0x3c3bb60, 0xc0000d4000})
	/go/pkg/mod/github.com/zinclabs/bluge@v1.1.5/reader.go:61 +0x83
github.com/zinclabs/zinc/pkg/bluge/search.MultiSearch.func3()
	/go/src/github.com/zinclabs/zinc/pkg/bluge/search/search.go:104 +0x4c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:72 +0xa5
```
**Which service(s) is this relate to?**
API

**Comment by almartino** [comment]
I figured out what can cause this issue:
```bash
curl -H "Authorization: Basic xxx" -X POST "localhost:4080/es/INDEX/_search" -d '{"size": -10}'
```
When requesting a negative size bluge crashes:
```
// https://github.com/blugelabs/bluge/blob/fe1f453e701a72cb3ee01b13b8a5e5f6e2b0f6cc/search/collector/topn_test.go
// Below my unit test (failing)
func TestBadCap(t *testing.T) {
	defer func() {
		if err := recover(); err != nil {
			t.Fatal("panic due to wrong topNCollector initialization")
		}
	}()
	NewTopNCollector(-10, 0, search.SortOrder{search.SortBy(search.DocumentScore()).Desc()})
}
```
[Here](https://github.com/blugelabs/bluge/blob/57414197005148539c5dc5db8ab581594969df79/search/collector/topn.go#L102) the problem: the function `newStoreSlice` tries to initialize a slice with a negative cap:
```go
rv := &collectStoreSlice{
  slice:   make(search.DocumentMatchCollection, 0, capacity), <-- cap is negative
  compare: compare,
}
```
Also, as I wrote on the first comment my query size is set to `q.SetSize(1)`... So the question is, how is possible that `NewTopNCollector` receives a negative value?

Something similar: blugelabs/bluge#129

@mschoch

**Comment by almartino** [comment]
I figured out the problem. I was parsing `size` and `from` on my backend assigning both to `-1`, indeed, if you invoke this api:
```bash
curl -H "Authorization: Basic xxx" -X POST "localhost:4080/es/INDEX/_search" -d '{"size": -1, "from": -1}'
```
The service will panic. The issue can be closed for me but I think the panic should be investigated more because the situation below is not yet clear for me:
```go
// github.com/zinclabs/bluge/search/collector/topn.go newTopNCollector
// pre-allocate space on the store to avoid reslicing
// unless the size + skip is too large, then cap it
// everything should still work, just reslices as necessary
hc.backingSize = size + skip + 1 <-- backingSize is the capacity passed to collectStoreSlice
if size+skip > PreAllocSizeSkipCap {
  hc.backingSize = PreAllocSizeSkipCap + 1
}
```

**Comment by hengfeiyang** [comment]
We don't support using a negative number for `from` or `size`, we will fix it.

**Comment by jonasgeiregat** [comment]
I could add a simple guard here that prevents this from occurring while giving the user some feedback if it would happen again.
